// Generated by CoffeeScript 1.7.0
(function() {
  var APDialog, APPlugin, ModalDialog, createSelector,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ModalDialog = require('voxel-modal-dialog');

  createSelector = require('artpacks-ui');

  module.exports = function(game, opts) {
    return new APPlugin(game, opts);
  };

  module.exports.pluginInfo = {
    clientOnly: true
  };

  APPlugin = (function() {
    function APPlugin(game, opts) {
      var _ref, _ref1;
      this.game = game;
      if (((_ref = this.game.materials) != null ? _ref.artPacks : void 0) == null) {
        throw 'voxel-artpacks requires game.materials with artPacks (voxel-texture-shader)';
      }
      if (((_ref1 = this.game.buttons) != null ? _ref1.down : void 0) == null) {
        throw 'voxel-artpacks requires game.buttons with kb-bindings';
      }
      this.dialog = new APDialog(this.game);
      this.enable();
    }

    APPlugin.prototype.enable = function() {
      return this.game.buttons.down.on('packs', this.onDown = this.dialog.open.bind(this.dialog));
    };

    APPlugin.prototype.disable = function() {
      if (this.onDown != null) {
        return this.game.buttons.down.removeListener('packs', this.onDown);
      }
    };

    return APPlugin;

  })();

  APDialog = (function(_super) {
    __extends(APDialog, _super);

    function APDialog(game) {
      var contents, refreshButton, selector;
      this.game = game;
      contents = [];
      contents.push(document.createTextNode('Drag packs below to change priority, or drop a .zip to load new pack:'));
      selector = createSelector(this.game.materials.artPacks);
      selector.container.style.margin = '5px';
      contents.push(selector.container);
      refreshButton = document.createElement('button');
      refreshButton.textContent = 'Preview';
      refreshButton.style.width = '100%';
      refreshButton.addEventListener('click', (function(_this) {
        return function(ev) {
          var i, old_names;
          old_names = _this.game.materials.names;
          _this.game.texture_opts.game = self.game;
          i = 0;
          _this.game.materials = _this.game.texture_modules[i](_this.game.texture_opts);
          _this.game.materials.load(old_names);
          return _this.game.showAllChunks();
        };
      })(this));
      contents.push(refreshButton);
      APDialog.__super__.constructor.call(this, game, {
        contents: contents,
        escapeKeys: [192, 80]
      });
    }

    return APDialog;

  })(ModalDialog);

}).call(this);
